### ISSUE TITLE
MDP Packet structure

### ISSUE THREAD

**Issue by error404-personnotfound** [servalproject/serval-docs#4]
what are the fields ST, RB, 1H, E and S in the MDP pack=ket and what are they used for?
What is broadcast id and RX id?
Why is the bit length 33 whereas it should have been 32

![image](https://user-images.githubusercontent.com/30428236/33078963-4c671066-cefa-11e7-84b1-f483b5f52513.png)

**Comment by gardners** [comment]
Where did you obtain the diagram?

Paul.

**Comment by lakeman** [comment]
The use of those bit flags is explained in the diagram. In our source code they are named PAYLOAD_FLAG_*.

Unicast traffic has 4 associated addresses, sender / recipient of the payload. transmitter / receiver of the packet. Though pairs of these addresses are often the same. Broadcast traffic has an ID to drop duplicates that might be heard from other peers.

All addresses are parsed with a 1 byte prefix code / length field, which may be followed by the full 32 bytes of the elliptic curve keys we are using;
https://github.com/servalproject/serval-dna/blob/development/overlay_address.c#L357

Here's where we generate / parse the raw bytes;
https://github.com/servalproject/serval-dna/blob/development/overlay_payload.c#L26
https://github.com/servalproject/serval-dna/blob/development/overlay_packetformats.c#L146

**Comment by quixotique** [comment]
That diagram comes from the wiki page http://developer.servalproject.org/dokuwiki/doku.php?id=content:tech:mdp and comes from the LCA 2013 conference slides.  It is out of date now, superseded by the technical document at https://github.com/servalproject/serval-dna/blob/development/doc/Mesh-Datagram-Protocol.md

**Comment by quixotique** [comment]
Fixed by https://github.com/servalproject/serval-dna/commit/7edf1a912e0c1760a1e8c2bff5afeb52fb844405

That wiki page now only contains a link to the tech document on GitHub.
